### ISSUE TITLE
Are the results in HiNet and DeepMIH tested on RGB or Y,U,V?

### ISSUE THREAD

**Issue by bumandpunk** [TomTomTommi/DeepMIH#3]
Hi! Thank you for sharing your code! Are the results in HiNet and DeepMIH tested on RGB or Y,U,V?  When we reproduced HiNet, we found that the results in the paper could not be reproduced, and the PSNR in the log file given by HiNet's official code did not reach that in the paper.  When we use the provided DeepMIH model to test, PSNR also does not achieve the results in the paper.  Since we were all testing in RGB, and the code included testing on Y, this was questionable.

**Comment by TomTomTommi** [comment]
Thanks for your interest. 
All the results are tested on Y. 
The training log is a demo to illustrate how to converge the network, the final results still need to be fine-tuned.

**Comment by bumandpunk** [comment]
> Thanks for your interest. All the results are tested on Y. The training log is a demo to illustrate how to converge the network, the final results still need to be fine-tuned.


Thank you for your answer
